'use client';
import { useState, useMemo } from 'react';
import ToolLayout from '../../components/ToolLayout';
import { btnPrimary, btnSecondary, labelClass, selectClass } from '../../components/styles';

const PRESETS = {
  static: { label: 'Static Site / SPA', icon: '📄' },
  reverseProxy: { label: 'Reverse Proxy (Node / Go / Python)', icon: '🔀' },
  php: { label: 'PHP-FPM (Laravel / WordPress)', icon: '🐘' },
  loadBalancer: { label: 'Load Balancer', icon: '⚖️' },
};

const PHP_VERSIONS = ['8.3', '8.2', '8.1', '8.0', '7.4'];

const SECURITY_HEADERS = [
  { id: 'xframe', label: 'X-Frame-Options', directive: 'add_header X-Frame-Options "SAMEORIGIN" always;' },
  { id: 'xcontent', label: 'X-Content-Type-Options', directive: 'add_header X-Content-Type-Options "nosniff" always;' },
  { id: 'xxss', label: 'X-XSS-Protection', directive: 'add_header X-XSS-Protection "1; mode=block" always;' },
  { id: 'referrer', label: 'Referrer-Policy', directive: 'add_header Referrer-Policy "strict-origin-when-cross-origin" always;' },
  { id: 'permissions', label: 'Permissions-Policy', directive: 'add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;' },
];

function checkbox(label, checked, onChange) {
  return (
    <label className="flex items-center gap-2 text-sm text-dark-200 cursor-pointer select-none">
      <input type="checkbox" checked={checked} onChange={e => onChange(e.target.checked)}
        className="w-3.5 h-3.5 rounded border-dark-600 bg-dark-800 accent-brand-500" />
      {label}
    </label>
  );
}

export default function NginxConfigClient() {
  const [preset, setPreset] = useState('reverseProxy');
  const [domain, setDomain] = useState('example.com');
  const [wwwRedirect, setWwwRedirect] = useState(true);
  const [ssl, setSsl] = useState(true);
  const [sslType, setSslType] = useState('letsencrypt');
  const [http2, setHttp2] = useState(true);
  const [hsts, setHsts] = useState(true);
  const [httpRedirect, setHttpRedirect] = useState(true);

  // Reverse proxy
  const [proxyHost, setProxyHost] = useState('127.0.0.1');
  const [proxyPort, setProxyPort] = useState('3000');
  const [websocket, setWebsocket] = useState(false);

  // Static
  const [rootPath, setRootPath] = useState('/var/www/html');
  const [spa, setSpa] = useState(false);

  // PHP
  const [phpVersion, setPhpVersion] = useState('8.3');
  const [phpSocket, setPhpSocket] = useState('unix');

  // Load balancer
  const [lbMethod, setLbMethod] = useState('round_robin');
  const [backends, setBackends] = useState([
    { host: '10.0.0.1', port: '8080', weight: '1' },
    { host: '10.0.0.2', port: '8080', weight: '1' },
  ]);

  // Performance
  const [gzip, setGzip] = useState(true);
  const [caching, setCaching] = useState(true);
  const [clientMaxBody, setClientMaxBody] = useState('64');
  const [workerConnections, setWorkerConnections] = useState('1024');

  // Security
  const [secHeaders, setSecHeaders] = useState({ xframe: true, xcontent: true, xxss: true, referrer: true, permissions: false });
  const [rateLimit, setRateLimit] = useState(false);
  const [rateLimitRps, setRateLimitRps] = useState('10');

  // Logging
  const [accessLog, setAccessLog] = useState(true);
  const [errorLog, setErrorLog] = useState(true);

  const [copied, setCopied] = useState(false);

  const config = useMemo(() => {
    const lines = [];
    const ind = (n, s) => '    '.repeat(n) + s;

    // --- events/worker block ---
    lines.push('# Generated by DevToolKit — https://www.devtoolkit.site/nginx-config/');
    lines.push('');

    if (preset === 'loadBalancer') {
      lines.push('# Main nginx.conf settings (add to nginx.conf or include)');
      lines.push(`worker_processes auto;`);
      lines.push('');
      lines.push('events {');
      lines.push(`    worker_connections ${workerConnections};`);
      lines.push('}');
      lines.push('');
      lines.push('http {');
    }

    // Rate limiting zone
    if (rateLimit) {
      lines.push(`# Rate limiting`);
      lines.push(`limit_req_zone $binary_remote_addr zone=ratelimit:10m rate=${rateLimitRps}r/s;`);
      lines.push('');
    }

    // --- upstream block (load balancer) ---
    if (preset === 'loadBalancer') {
      lines.push(`    upstream backend {`);
      if (lbMethod === 'least_conn') lines.push(`        least_conn;`);
      if (lbMethod === 'ip_hash') lines.push(`        ip_hash;`);
      backends.forEach(b => {
        const w = b.weight !== '1' ? ` weight=${b.weight}` : '';
        lines.push(`        server ${b.host}:${b.port}${w};`);
      });
      lines.push(`    }`);
      lines.push('');
    }

    // --- HTTP → HTTPS redirect ---
    if (ssl && httpRedirect) {
      if (preset === 'loadBalancer') lines.push('    server {');
      else lines.push('server {');
      const p = preset === 'loadBalancer' ? '        ' : '    ';
      lines.push(`${p}listen 80;`);
      lines.push(`${p}listen [::]:80;`);
      lines.push(`${p}server_name ${domain}${wwwRedirect ? ' www.' + domain : ''};`);
      lines.push(`${p}return 301 https://$host$request_uri;`);
      if (preset === 'loadBalancer') lines.push('    }');
      else lines.push('}');
      lines.push('');
    }

    // --- www redirect ---
    if (wwwRedirect && ssl) {
      if (preset === 'loadBalancer') lines.push('    server {');
      else lines.push('server {');
      const p = preset === 'loadBalancer' ? '        ' : '    ';
      lines.push(`${p}listen 443 ssl${http2 ? ' http2' : ''};`);
      lines.push(`${p}listen [::]:443 ssl${http2 ? ' http2' : ''};`);
      lines.push(`${p}server_name www.${domain};`);
      lines.push('');
      if (sslType === 'letsencrypt') {
        lines.push(`${p}ssl_certificate /etc/letsencrypt/live/${domain}/fullchain.pem;`);
        lines.push(`${p}ssl_certificate_key /etc/letsencrypt/live/${domain}/privkey.pem;`);
      } else {
        lines.push(`${p}ssl_certificate /etc/nginx/ssl/${domain}.crt;`);
        lines.push(`${p}ssl_certificate_key /etc/nginx/ssl/${domain}.key;`);
      }
      lines.push('');
      lines.push(`${p}return 301 https://${domain}$request_uri;`);
      if (preset === 'loadBalancer') lines.push('    }');
      else lines.push('}');
      lines.push('');
    }

    // --- Main server block ---
    const pfx = preset === 'loadBalancer' ? '    ' : '';
    lines.push(`${pfx}server {`);
    const p = pfx + '    ';

    // Listen
    if (ssl) {
      lines.push(`${p}listen 443 ssl${http2 ? ' http2' : ''};`);
      lines.push(`${p}listen [::]:443 ssl${http2 ? ' http2' : ''};`);
    } else {
      lines.push(`${p}listen 80;`);
      lines.push(`${p}listen [::]:80;`);
    }
    lines.push(`${p}server_name ${domain};`);
    lines.push('');

    // SSL config
    if (ssl) {
      if (sslType === 'letsencrypt') {
        lines.push(`${p}# SSL — Let's Encrypt`);
        lines.push(`${p}ssl_certificate /etc/letsencrypt/live/${domain}/fullchain.pem;`);
        lines.push(`${p}ssl_certificate_key /etc/letsencrypt/live/${domain}/privkey.pem;`);
        lines.push(`${p}ssl_trusted_certificate /etc/letsencrypt/live/${domain}/chain.pem;`);
      } else {
        lines.push(`${p}# SSL — Custom certificate`);
        lines.push(`${p}ssl_certificate /etc/nginx/ssl/${domain}.crt;`);
        lines.push(`${p}ssl_certificate_key /etc/nginx/ssl/${domain}.key;`);
      }
      lines.push('');
      lines.push(`${p}# SSL settings`);
      lines.push(`${p}ssl_protocols TLSv1.2 TLSv1.3;`);
      lines.push(`${p}ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384';`);
      lines.push(`${p}ssl_prefer_server_ciphers off;`);
      lines.push(`${p}ssl_session_cache shared:SSL:10m;`);
      lines.push(`${p}ssl_session_timeout 1d;`);
      lines.push(`${p}ssl_session_tickets off;`);
      if (sslType === 'letsencrypt') {
        lines.push(`${p}ssl_stapling on;`);
        lines.push(`${p}ssl_stapling_verify on;`);
        lines.push(`${p}resolver 1.1.1.1 8.8.8.8 valid=300s;`);
      }
      lines.push('');
    }

    // Root (static / PHP)
    if (preset === 'static' || preset === 'php') {
      lines.push(`${p}root ${rootPath};`);
      lines.push(`${p}index index.html${preset === 'php' ? ' index.php' : ''};`);
      lines.push('');
    }

    // Security headers
    const activeHeaders = SECURITY_HEADERS.filter(h => secHeaders[h.id]);
    if (activeHeaders.length > 0 || (ssl && hsts)) {
      lines.push(`${p}# Security headers`);
      if (ssl && hsts) {
        lines.push(`${p}add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;`);
      }
      activeHeaders.forEach(h => lines.push(`${p}${h.directive}`));
      lines.push('');
    }

    // Rate limiting
    if (rateLimit) {
      lines.push(`${p}# Rate limiting`);
      lines.push(`${p}limit_req zone=ratelimit burst=20 nodelay;`);
      lines.push('');
    }

    // Client body size
    lines.push(`${p}client_max_body_size ${clientMaxBody}m;`);
    lines.push('');

    // Gzip
    if (gzip) {
      lines.push(`${p}# Gzip compression`);
      lines.push(`${p}gzip on;`);
      lines.push(`${p}gzip_vary on;`);
      lines.push(`${p}gzip_proxied any;`);
      lines.push(`${p}gzip_comp_level 5;`);
      lines.push(`${p}gzip_min_length 256;`);
      lines.push(`${p}gzip_types`);
      lines.push(`${p}    text/plain`);
      lines.push(`${p}    text/css`);
      lines.push(`${p}    text/javascript`);
      lines.push(`${p}    application/json`);
      lines.push(`${p}    application/javascript`);
      lines.push(`${p}    application/xml`);
      lines.push(`${p}    image/svg+xml;`);
      lines.push('');
    }

    // Static file caching
    if (caching && (preset === 'static' || preset === 'php')) {
      lines.push(`${p}# Static file caching`);
      lines.push(`${p}location ~* \\.(jpg|jpeg|png|gif|ico|svg|webp|woff2|woff|ttf|css|js)$ {`);
      lines.push(`${p}    expires 30d;`);
      lines.push(`${p}    add_header Cache-Control "public, immutable";`);
      lines.push(`${p}    access_log off;`);
      lines.push(`${p}}`);
      lines.push('');
    }

    // --- Location blocks by preset ---
    if (preset === 'static') {
      lines.push(`${p}location / {`);
      if (spa) {
        lines.push(`${p}    try_files $uri $uri/ /index.html;`);
      } else {
        lines.push(`${p}    try_files $uri $uri/ =404;`);
      }
      lines.push(`${p}}`);
    }

    if (preset === 'reverseProxy') {
      if (caching) {
        lines.push(`${p}# Static file caching (if serving static from nginx)`);
        lines.push(`${p}location /static/ {`);
        lines.push(`${p}    alias /var/www/${domain}/static/;`);
        lines.push(`${p}    expires 30d;`);
        lines.push(`${p}    add_header Cache-Control "public, immutable";`);
        lines.push(`${p}    access_log off;`);
        lines.push(`${p}}`);
        lines.push('');
      }
      lines.push(`${p}location / {`);
      lines.push(`${p}    proxy_pass http://${proxyHost}:${proxyPort};`);
      lines.push(`${p}    proxy_http_version 1.1;`);
      lines.push(`${p}    proxy_set_header Host $host;`);
      lines.push(`${p}    proxy_set_header X-Real-IP $remote_addr;`);
      lines.push(`${p}    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`);
      lines.push(`${p}    proxy_set_header X-Forwarded-Proto $scheme;`);
      if (websocket) {
        lines.push('');
        lines.push(`${p}    # WebSocket support`);
        lines.push(`${p}    proxy_set_header Upgrade $http_upgrade;`);
        lines.push(`${p}    proxy_set_header Connection "upgrade";`);
        lines.push(`${p}    proxy_read_timeout 86400;`);
      }
      lines.push(`${p}}`);
    }

    if (preset === 'php') {
      lines.push(`${p}location / {`);
      lines.push(`${p}    try_files $uri $uri/ /index.php?$query_string;`);
      lines.push(`${p}}`);
      lines.push('');
      const sock = phpSocket === 'unix'
        ? `unix:/run/php/php${phpVersion}-fpm.sock`
        : `127.0.0.1:9000`;
      lines.push(`${p}location ~ \\.php$ {`);
      lines.push(`${p}    fastcgi_pass ${sock};`);
      lines.push(`${p}    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;`);
      lines.push(`${p}    include fastcgi_params;`);
      lines.push(`${p}    fastcgi_index index.php;`);
      lines.push(`${p}    fastcgi_buffers 16 16k;`);
      lines.push(`${p}    fastcgi_buffer_size 32k;`);
      lines.push(`${p}}`);
      lines.push('');
      lines.push(`${p}# Deny access to hidden files`);
      lines.push(`${p}location ~ /\\. {`);
      lines.push(`${p}    deny all;`);
      lines.push(`${p}    access_log off;`);
      lines.push(`${p}    log_not_found off;`);
      lines.push(`${p}}`);
    }

    if (preset === 'loadBalancer') {
      if (caching) {
        lines.push(`${p}# Proxy cache`);
        lines.push(`${p}proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=cache:10m max_size=1g inactive=60m;`);
        lines.push('');
      }
      lines.push(`${p}location / {`);
      lines.push(`${p}    proxy_pass http://backend;`);
      lines.push(`${p}    proxy_http_version 1.1;`);
      lines.push(`${p}    proxy_set_header Host $host;`);
      lines.push(`${p}    proxy_set_header X-Real-IP $remote_addr;`);
      lines.push(`${p}    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`);
      lines.push(`${p}    proxy_set_header X-Forwarded-Proto $scheme;`);
      lines.push(`${p}    proxy_next_upstream error timeout http_500 http_502 http_503;`);
      if (caching) {
        lines.push(`${p}    proxy_cache cache;`);
        lines.push(`${p}    proxy_cache_valid 200 10m;`);
        lines.push(`${p}    proxy_cache_use_stale error timeout updating;`);
      }
      lines.push(`${p}}`);
    }

    lines.push('');

    // Logging
    if (accessLog || errorLog) {
      lines.push(`${p}# Logging`);
      if (accessLog) lines.push(`${p}access_log /var/log/nginx/${domain}.access.log;`);
      else lines.push(`${p}access_log off;`);
      if (errorLog) lines.push(`${p}error_log /var/log/nginx/${domain}.error.log warn;`);
      lines.push('');
    }

    lines.push(`${pfx}}`);

    if (preset === 'loadBalancer') {
      lines.push('}');
    }

    return lines.join('\n');
  }, [preset, domain, wwwRedirect, ssl, sslType, http2, hsts, httpRedirect, proxyHost, proxyPort, websocket, rootPath, spa, phpVersion, phpSocket, lbMethod, backends, gzip, caching, clientMaxBody, workerConnections, secHeaders, rateLimit, rateLimitRps, accessLog, errorLog]);

  const copy = () => {
    navigator.clipboard.writeText(config);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const download = () => {
    const blob = new Blob([config], { type: 'text/plain' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `${domain.replace(/\./g, '_')}.conf`;
    a.click();
  };

  const updateBackend = (i, field, val) => {
    setBackends(prev => prev.map((b, j) => j === i ? { ...b, [field]: val } : b));
  };

  return (
    <ToolLayout title="Nginx Config Generator" description="Build optimized nginx.conf for any setup">
      {/* Preset selector */}
      <div className="mb-5">
        <div className={labelClass}>Server Type</div>
        <div className="grid grid-cols-2 gap-2">
          {Object.entries(PRESETS).map(([key, { label, icon }]) => (
            <button key={key} onClick={() => setPreset(key)}
              className={`text-left px-3 py-2.5 rounded-lg border text-sm transition-all ${
                preset === key
                  ? 'border-brand-500/50 bg-brand-500/10 text-brand-300'
                  : 'border-dark-700 bg-dark-800 text-dark-300 hover:border-dark-600'
              }`}>
              <span className="mr-1.5">{icon}</span> {label}
            </button>
          ))}
        </div>
      </div>

      {/* Domain */}
      <div className="grid grid-cols-2 gap-3 mb-4">
        <div>
          <div className={labelClass}>Domain</div>
          <input value={domain} onChange={e => setDomain(e.target.value)}
            className="w-full bg-dark-900 border border-dark-700 rounded-lg px-3 py-2 font-mono text-[13px] text-dark-100 outline-none" />
        </div>
        <div className="flex flex-col gap-2 pt-6">
          {checkbox('www → non-www redirect', wwwRedirect, setWwwRedirect)}
        </div>
      </div>

      {/* SSL */}
      <div className="bg-dark-800/50 border border-dark-700/50 rounded-lg p-3 mb-4">
        <div className="flex items-center gap-4 mb-2">
          {checkbox('Enable SSL / HTTPS', ssl, setSsl)}
        </div>
        {ssl && (
          <div className="grid grid-cols-2 gap-3 mt-2">
            <div>
              <div className={labelClass}>Certificate</div>
              <select value={sslType} onChange={e => setSslType(e.target.value)} className={selectClass}>
                <option value="letsencrypt">Let&apos;s Encrypt (certbot)</option>
                <option value="custom">Custom certificate</option>
              </select>
            </div>
            <div className="flex flex-col gap-2 pt-5">
              {checkbox('HTTP/2', http2, setHttp2)}
              {checkbox('HSTS header', hsts, setHsts)}
              {checkbox('HTTP → HTTPS redirect', httpRedirect, setHttpRedirect)}
            </div>
          </div>
        )}
      </div>

      {/* Preset-specific options */}
      {preset === 'reverseProxy' && (
        <div className="bg-dark-800/50 border border-dark-700/50 rounded-lg p-3 mb-4">
          <div className="text-xs font-semibold text-dark-400 mb-2 uppercase tracking-wider">Proxy Backend</div>
          <div className="grid grid-cols-3 gap-3">
            <div>
              <div className={labelClass}>Host</div>
              <input value={proxyHost} onChange={e => setProxyHost(e.target.value)}
                className="w-full bg-dark-900 border border-dark-700 rounded-lg px-3 py-2 font-mono text-[13px] text-dark-100 outline-none" />
            </div>
            <div>
              <div className={labelClass}>Port</div>
              <input value={proxyPort} onChange={e => setProxyPort(e.target.value)}
                className="w-full bg-dark-900 border border-dark-700 rounded-lg px-3 py-2 font-mono text-[13px] text-dark-100 outline-none" />
            </div>
            <div className="pt-5">
              {checkbox('WebSocket support', websocket, setWebsocket)}
            </div>
          </div>
        </div>
      )}

      {preset === 'static' && (
        <div className="bg-dark-800/50 border border-dark-700/50 rounded-lg p-3 mb-4">
          <div className="text-xs font-semibold text-dark-400 mb-2 uppercase tracking-wider">Static Site</div>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <div className={labelClass}>Root Path</div>
              <input value={rootPath} onChange={e => setRootPath(e.target.value)}
                className="w-full bg-dark-900 border border-dark-700 rounded-lg px-3 py-2 font-mono text-[13px] text-dark-100 outline-none" />
            </div>
            <div className="pt-5">
              {checkbox('SPA mode (try_files → index.html)', spa, setSpa)}
            </div>
          </div>
        </div>
      )}

      {preset === 'php' && (
        <div className="bg-dark-800/50 border border-dark-700/50 rounded-lg p-3 mb-4">
          <div className="text-xs font-semibold text-dark-400 mb-2 uppercase tracking-wider">PHP-FPM</div>
          <div className="grid grid-cols-3 gap-3">
            <div>
              <div className={labelClass}>PHP Version</div>
              <select value={phpVersion} onChange={e => setPhpVersion(e.target.value)} className={selectClass}>
                {PHP_VERSIONS.map(v => <option key={v} value={v}>{v}</option>)}
              </select>
            </div>
            <div>
              <div className={labelClass}>Connection</div>
              <select value={phpSocket} onChange={e => setPhpSocket(e.target.value)} className={selectClass}>
                <option value="unix">Unix Socket</option>
                <option value="tcp">TCP 127.0.0.1:9000</option>
              </select>
            </div>
            <div>
              <div className={labelClass}>Root Path</div>
              <input value={rootPath} onChange={e => setRootPath(e.target.value)}
                className="w-full bg-dark-900 border border-dark-700 rounded-lg px-3 py-2 font-mono text-[13px] text-dark-100 outline-none" />
            </div>
          </div>
        </div>
      )}

      {preset === 'loadBalancer' && (
        <div className="bg-dark-800/50 border border-dark-700/50 rounded-lg p-3 mb-4">
          <div className="text-xs font-semibold text-dark-400 mb-2 uppercase tracking-wider">Upstream Backends</div>
          <div className="mb-3">
            <div className={labelClass}>Method</div>
            <select value={lbMethod} onChange={e => setLbMethod(e.target.value)} className={selectClass}>
              <option value="round_robin">Round Robin (default)</option>
              <option value="least_conn">Least Connections</option>
              <option value="ip_hash">IP Hash (sticky sessions)</option>
            </select>
          </div>
          {backends.map((b, i) => (
            <div key={i} className="grid grid-cols-4 gap-2 mb-2 items-end">
              <div>
                <div className={labelClass}>Host</div>
                <input value={b.host} onChange={e => updateBackend(i, 'host', e.target.value)}
                  className="w-full bg-dark-900 border border-dark-700 rounded-lg px-2 py-1.5 font-mono text-[12px] text-dark-100 outline-none" />
              </div>
              <div>
                <div className={labelClass}>Port</div>
                <input value={b.port} onChange={e => updateBackend(i, 'port', e.target.value)}
                  className="w-full bg-dark-900 border border-dark-700 rounded-lg px-2 py-1.5 font-mono text-[12px] text-dark-100 outline-none" />
              </div>
              <div>
                <div className={labelClass}>Weight</div>
                <input value={b.weight} onChange={e => updateBackend(i, 'weight', e.target.value)}
                  className="w-full bg-dark-900 border border-dark-700 rounded-lg px-2 py-1.5 font-mono text-[12px] text-dark-100 outline-none" />
              </div>
              <button onClick={() => setBackends(prev => prev.filter((_, j) => j !== i))}
                className="text-red-400 text-xs hover:text-red-300 pb-1.5" disabled={backends.length <= 1}>✕ Remove</button>
            </div>
          ))}
          {backends.length < 8 && (
            <button onClick={() => setBackends(prev => [...prev, { host: `10.0.0.${prev.length + 1}`, port: '8080', weight: '1' }])}
              className="text-brand-400 text-xs mt-1 hover:text-brand-300">+ Add backend</button>
          )}
        </div>
      )}

      {/* Performance */}
      <div className="bg-dark-800/50 border border-dark-700/50 rounded-lg p-3 mb-4">
        <div className="text-xs font-semibold text-dark-400 mb-2 uppercase tracking-wider">Performance</div>
        <div className="grid grid-cols-2 gap-3">
          <div className="flex flex-col gap-2">
            {checkbox('Gzip compression', gzip, setGzip)}
            {checkbox('Static file caching (30d)', caching, setCaching)}
          </div>
          <div className="grid grid-cols-2 gap-2">
            <div>
              <div className={labelClass}>Max Body (MB)</div>
              <input value={clientMaxBody} onChange={e => setClientMaxBody(e.target.value)}
                className="w-full bg-dark-900 border border-dark-700 rounded-lg px-2 py-1.5 font-mono text-[12px] text-dark-100 outline-none" />
            </div>
            {preset === 'loadBalancer' && (
              <div>
                <div className={labelClass}>Worker Conns</div>
                <input value={workerConnections} onChange={e => setWorkerConnections(e.target.value)}
                  className="w-full bg-dark-900 border border-dark-700 rounded-lg px-2 py-1.5 font-mono text-[12px] text-dark-100 outline-none" />
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Security */}
      <div className="bg-dark-800/50 border border-dark-700/50 rounded-lg p-3 mb-4">
        <div className="text-xs font-semibold text-dark-400 mb-2 uppercase tracking-wider">Security Headers</div>
        <div className="grid grid-cols-2 gap-2">
          {SECURITY_HEADERS.map(h => (
            <div key={h.id}>
              {checkbox(h.label, secHeaders[h.id], v => setSecHeaders(prev => ({ ...prev, [h.id]: v })))}
            </div>
          ))}
          <div>
            {checkbox(`Rate limiting (${rateLimitRps} req/s)`, rateLimit, setRateLimit)}
          </div>
        </div>
        {rateLimit && (
          <div className="mt-2 w-32">
            <div className={labelClass}>Requests/sec</div>
            <input value={rateLimitRps} onChange={e => setRateLimitRps(e.target.value)}
              className="w-full bg-dark-900 border border-dark-700 rounded-lg px-2 py-1.5 font-mono text-[12px] text-dark-100 outline-none" />
          </div>
        )}
      </div>

      {/* Logging */}
      <div className="flex gap-4 mb-5">
        {checkbox('Access log', accessLog, setAccessLog)}
        {checkbox('Error log', errorLog, setErrorLog)}
      </div>

      {/* Output */}
      <div className="flex items-center gap-2 mb-2">
        <div className="text-xs font-semibold text-dark-400 uppercase tracking-wider flex-1">Generated nginx.conf</div>
        <button onClick={copy} className={btnPrimary + ' text-xs !px-3 !py-1.5'}>
          {copied ? '✓ Copied' : 'Copy'}
        </button>
        <button onClick={download} className={btnSecondary + ' text-xs !px-3 !py-1.5'}>
          Download .conf
        </button>
      </div>
      <pre className="bg-dark-900 rounded-lg p-4 border border-dark-700 font-mono text-[12px] text-dark-100 overflow-auto max-h-[600px] leading-relaxed whitespace-pre">
        {config}
      </pre>

      {/* Pipeline visualization */}
      <div className="mt-4 flex flex-wrap gap-1.5">
        {ssl && httpRedirect && (
          <span className="bg-yellow-500/10 text-yellow-400 border border-yellow-500/20 text-[10px] px-2 py-1 rounded-full">HTTP:80 → HTTPS</span>
        )}
        {wwwRedirect && (
          <span className="bg-blue-500/10 text-blue-400 border border-blue-500/20 text-[10px] px-2 py-1 rounded-full">www → non-www</span>
        )}
        {ssl && (
          <span className="bg-green-500/10 text-green-400 border border-green-500/20 text-[10px] px-2 py-1 rounded-full">SSL/TLS {http2 ? '+ HTTP/2' : ''}</span>
        )}
        {gzip && (
          <span className="bg-purple-500/10 text-purple-400 border border-purple-500/20 text-[10px] px-2 py-1 rounded-full">Gzip</span>
        )}
        {rateLimit && (
          <span className="bg-red-500/10 text-red-400 border border-red-500/20 text-[10px] px-2 py-1 rounded-full">Rate Limit {rateLimitRps}r/s</span>
        )}
        <span className="bg-brand-500/10 text-brand-400 border border-brand-500/20 text-[10px] px-2 py-1 rounded-full">
          {PRESETS[preset].icon} {PRESETS[preset].label}
        </span>
      </div>

      {/* Variables warning */}
      {ssl && sslType === 'letsencrypt' && (
        <div className="mt-4 bg-yellow-500/5 border border-yellow-500/20 rounded-lg px-4 py-3">
          <div className="text-xs font-semibold text-yellow-400 mb-1">⚠ Setup required</div>
          <div className="text-[11px] text-dark-400 space-y-1">
            <p>Install certbot: <code className="text-dark-300">sudo apt install certbot python3-certbot-nginx</code></p>
            <p>Get certificate: <code className="text-dark-300">sudo certbot --nginx -d {domain}{wwwRedirect ? ` -d www.${domain}` : ''}</code></p>
            <p>Auto-renewal is configured automatically by certbot.</p>
          </div>
        </div>
      )}

      {/* SEO content */}
      <section className="mt-10 border-t border-dark-700 pt-6">
        <h2 className="text-base font-bold text-dark-200 mb-3">Nginx Configuration Generator — Build Production-Ready Configs</h2>
        <div className="text-xs text-dark-400 leading-relaxed space-y-2">
          <p>This tool generates optimized Nginx configuration files for the most common server setups: reverse proxy for Node.js, Go, and Python backends, static file hosting and single-page applications (React, Vue, Next.js), PHP-FPM for Laravel and WordPress, and load balancing across multiple servers. Each generated config includes SSL/TLS best practices, gzip compression, security headers, and proper logging.</p>

          <h3 className="text-sm font-semibold text-dark-300 mt-4 mb-2">Nginx as a Reverse Proxy</h3>
          <p>The most common Nginx use case is reverse proxying to a backend application. The <code className="text-dark-300">proxy_pass</code> directive forwards requests to your Node.js (Express, Fastify), Go (Gin, Echo), Python (Django, Flask, FastAPI), or any HTTP backend. Key headers to pass: <code className="text-dark-300">X-Real-IP</code> for the client&apos;s real IP, <code className="text-dark-300">X-Forwarded-For</code> for proxy chain tracking, and <code className="text-dark-300">X-Forwarded-Proto</code> so the backend knows if the original request was HTTPS.</p>

          <h3 className="text-sm font-semibold text-dark-300 mt-4 mb-2">SSL/TLS Configuration</h3>
          <p>Modern SSL config should use <strong className="text-dark-300">TLSv1.2 and TLSv1.3</strong> only (TLSv1.0 and 1.1 are deprecated). Enable <strong className="text-dark-300">OCSP stapling</strong> to speed up certificate validation, configure <strong className="text-dark-300">session caching</strong> to reduce TLS handshake overhead, and add the <strong className="text-dark-300">HSTS header</strong> to tell browsers to always use HTTPS. For <strong className="text-dark-300">Let&apos;s Encrypt</strong>, certbot handles certificate issuance and auto-renewal.</p>

          <h3 className="text-sm font-semibold text-dark-300 mt-4 mb-2">Gzip Best Practices</h3>
          <p>Enable <code className="text-dark-300">gzip</code> with compression level 5 (good balance of speed vs size). Set <code className="text-dark-300">gzip_min_length 256</code> to skip tiny files where compression overhead exceeds savings. Include all text-based MIME types: CSS, JavaScript, JSON, XML, SVG. Don&apos;t compress already-compressed formats (JPEG, PNG, WOFF2) — it wastes CPU for zero benefit.</p>

          <h3 className="text-sm font-semibold text-dark-300 mt-4 mb-2">Load Balancing Methods</h3>
          <p><strong className="text-dark-300">Round Robin</strong> (default) distributes requests equally. <strong className="text-dark-300">Least Connections</strong> sends traffic to the server with fewest active connections — better when request processing times vary. <strong className="text-dark-300">IP Hash</strong> ensures the same client always hits the same backend — useful for session-based apps without shared session storage.</p>

          <h3 className="text-sm font-semibold text-dark-300 mt-4 mb-2">Nginx Security Headers</h3>
          <p><strong className="text-dark-300">X-Frame-Options: SAMEORIGIN</strong> prevents clickjacking by blocking iframe embedding from other domains. <strong className="text-dark-300">X-Content-Type-Options: nosniff</strong> stops browsers from MIME-sniffing responses. <strong className="text-dark-300">Referrer-Policy</strong> controls how much referrer information is sent with requests. These headers are free performance and security wins — no reason not to enable them.</p>

          <p>All configuration is generated in your browser — nothing is sent to any server. Use the generated config as a starting point and adjust for your specific needs.</p>

          <p className="mt-3"><strong className="text-dark-300">Want detailed explanations with examples?</strong> Read our <a href="/blog/nginx-configuration-guide/" className="text-brand-400 hover:underline">Nginx Configuration Guide for Developers</a> — reverse proxy, SSL, gzip, load balancing, and security headers with copy-paste configs.</p>
        </div>
      </section>
    </ToolLayout>
  );
}
