'use client';
import { useState, useMemo, useCallback } from 'react';
import ToolLayout from '../../components/ToolLayout';
import { btnPrimary, btnSecondary, labelClass, selectClass } from '../../components/styles';

const LANGUAGES = [
  { id: 'nodejs', label: 'Node.js', icon: '⬢', image: 'node:20-alpine', versions: ['22', '20', '18', '16'], lint: 'npm run lint', test: 'npm test', build: 'npm run build', install: 'npm ci', cache: 'node_modules/', lockfile: 'package-lock.json' },
  { id: 'python', label: 'Python', icon: '🐍', image: 'python:3.12-slim', versions: ['3.13', '3.12', '3.11', '3.10', '3.9'], lint: 'flake8 . && mypy .', test: 'pytest --cov', build: null, install: 'pip install -r requirements.txt', cache: '.pip-cache/', lockfile: 'requirements.txt' },
  { id: 'go', label: 'Go', icon: '🔵', image: 'golang:1.23-alpine', versions: ['1.23', '1.22', '1.21', '1.20'], lint: 'golangci-lint run', test: 'go test ./...', build: 'CGO_ENABLED=0 go build -ldflags="-s -w" -o app ./cmd/...', install: 'go mod download', cache: '/go/pkg/mod/', lockfile: 'go.sum' },
  { id: 'java', label: 'Java (Maven)', icon: '☕', image: 'maven:3.9-eclipse-temurin-21', versions: ['21', '17', '11'], lint: 'mvn checkstyle:check', test: 'mvn test', build: 'mvn package -DskipTests', install: null, cache: '.m2/repository/', lockfile: 'pom.xml' },
  { id: 'java-gradle', label: 'Java (Gradle)', icon: '☕', image: 'gradle:8-jdk21', versions: ['21', '17', '11'], lint: 'gradle checkstyleMain', test: 'gradle test', build: 'gradle build -x test', install: null, cache: '.gradle/', lockfile: 'build.gradle' },
  { id: 'rust', label: 'Rust', icon: '🦀', image: 'rust:1.80-slim', versions: ['1.80', '1.78', '1.75'], lint: 'cargo clippy -- -D warnings', test: 'cargo test', build: 'cargo build --release', install: null, cache: 'target/', lockfile: 'Cargo.lock' },
  { id: 'php', label: 'PHP', icon: '🐘', image: 'php:8.3-cli', versions: ['8.3', '8.2', '8.1'], lint: 'vendor/bin/phpstan analyse', test: 'vendor/bin/phpunit', build: null, install: 'composer install --no-dev --optimize-autoloader', cache: 'vendor/', lockfile: 'composer.lock' },
  { id: 'ruby', label: 'Ruby', icon: '💎', image: 'ruby:3.3-slim', versions: ['3.3', '3.2', '3.1'], lint: 'bundle exec rubocop', test: 'bundle exec rspec', build: null, install: 'bundle install', cache: 'vendor/ruby/', lockfile: 'Gemfile.lock' },
  { id: 'dotnet', label: '.NET', icon: '🔷', image: 'mcr.microsoft.com/dotnet/sdk:8.0', versions: ['9.0', '8.0', '7.0', '6.0'], lint: 'dotnet format --verify-no-changes', test: 'dotnet test', build: 'dotnet publish -c Release -o out', install: 'dotnet restore', cache: null, lockfile: null },
  { id: 'docker', label: 'Docker Only', icon: '🐳', image: 'docker:27', versions: [], lint: 'hadolint Dockerfile', test: null, build: null, install: null, cache: null, lockfile: null },
];

const DEPLOY_TARGETS = [
  { id: 'none', label: 'No Deploy', desc: 'Build & test only' },
  { id: 'docker-registry', label: 'Docker Registry', desc: 'Push image to registry (DockerHub, GitLab, GHCR)' },
  { id: 'kubernetes', label: 'Kubernetes', desc: 'Deploy via kubectl apply' },
  { id: 'ssh', label: 'SSH / VPS', desc: 'Deploy via SSH to remote server' },
  { id: 'aws-ecs', label: 'AWS ECS', desc: 'Update ECS service with new image' },
  { id: 'pages', label: 'GitLab Pages', desc: 'Deploy static site to GitLab Pages' },
  { id: 'heroku', label: 'Heroku', desc: 'Push to Heroku container registry' },
  { id: 's3', label: 'AWS S3 + CloudFront', desc: 'Sync static files to S3 bucket' },
];

const SERVICES = [
  { id: 'postgres', label: 'PostgreSQL', image: 'postgres:16-alpine', envs: { POSTGRES_DB: 'test_db', POSTGRES_USER: 'test', POSTGRES_PASSWORD: 'test' }, dbUrl: 'postgresql://test:test@postgres:5432/test_db' },
  { id: 'mysql', label: 'MySQL', image: 'mysql:8.0', envs: { MYSQL_DATABASE: 'test_db', MYSQL_ROOT_PASSWORD: 'test' }, dbUrl: 'mysql://root:test@mysql:3306/test_db' },
  { id: 'redis', label: 'Redis', image: 'redis:7-alpine', envs: {}, dbUrl: 'redis://redis:6379' },
  { id: 'mongodb', label: 'MongoDB', image: 'mongo:7', envs: {}, dbUrl: 'mongodb://mongo:27017/test_db' },
];

function generateYAML(config) {
  const lang = LANGUAGES.find(l => l.id === config.language);
  const lines = [];
  const add = (s = '') => lines.push(s);
  const comment = (s) => lines.push(`# ${s}`);

  // Header
  comment('=================================================');
  comment(` GitLab CI/CD Pipeline — ${lang.label}`);
  comment(' Generated by DevToolKit (devtoolkit.site)');
  comment('=================================================');
  add();

  // Stages
  const stages = [];
  if (config.lint) stages.push('lint');
  if (config.test) stages.push('test');
  if (config.build) stages.push('build');
  if (config.deploy !== 'none') stages.push('deploy');
  add('stages:');
  stages.forEach(s => add(`  - ${s}`));
  add();

  // Variables
  const vars = {};
  if (config.language === 'python') {
    vars.PIP_CACHE_DIR = '"$CI_PROJECT_DIR/.pip-cache"';
  }
  if (config.language === 'go') {
    vars.GOPATH = '"$CI_PROJECT_DIR/.go"';
  }
  if (config.deploy === 'docker-registry' || config.deploy === 'kubernetes' || config.deploy === 'aws-ecs' || config.deploy === 'heroku') {
    vars.DOCKER_IMAGE = `"$CI_REGISTRY_IMAGE"`;
    vars.DOCKER_TAG = `"$CI_COMMIT_SHORT_SHA"`;
  }
  if (config.services.includes('postgres')) {
    vars.DATABASE_URL = `"${SERVICES.find(s => s.id === 'postgres').dbUrl}"`;
  }
  if (config.services.includes('mysql')) {
    vars.DATABASE_URL = `"${SERVICES.find(s => s.id === 'mysql').dbUrl}"`;
  }
  if (config.services.includes('redis')) {
    vars.REDIS_URL = `"${SERVICES.find(s => s.id === 'redis').dbUrl}"`;
  }
  if (config.services.includes('mongodb')) {
    vars.MONGO_URL = `"${SERVICES.find(s => s.id === 'mongodb').dbUrl}"`;
  }

  if (Object.keys(vars).length > 0) {
    add('variables:');
    Object.entries(vars).forEach(([k, v]) => add(`  ${k}: ${v}`));
    add();
  }

  // Default image
  if (config.language !== 'docker') {
    const img = lang.image.replace(/:\d+(\.\d+)?/, ':' + config.version);
    // For some images the version format is different
    let image = lang.image;
    if (config.language === 'nodejs') image = `node:${config.version}-alpine`;
    else if (config.language === 'python') image = `python:${config.version}-slim`;
    else if (config.language === 'go') image = `golang:${config.version}-alpine`;
    else if (config.language === 'java') image = `maven:3.9-eclipse-temurin-${config.version}`;
    else if (config.language === 'java-gradle') image = `gradle:8-jdk${config.version}`;
    else if (config.language === 'rust') image = `rust:${config.version}-slim`;
    else if (config.language === 'php') image = `php:${config.version}-cli`;
    else if (config.language === 'ruby') image = `ruby:${config.version}-slim`;
    else if (config.language === 'dotnet') image = `mcr.microsoft.com/dotnet/sdk:${config.version}`;

    add(`image: ${image}`);
    add();
  }

  // Cache
  if (lang.cache && config.cache) {
    add('cache:');
    add('  key: "$CI_COMMIT_REF_SLUG"');
    add('  paths:');
    add(`    - ${lang.cache}`);
    if (config.language === 'python') add('    - .pip-cache/');
    if (config.language === 'go') add('    - .go/pkg/mod/');
    add();
  }

  // Before script (install deps)
  if (lang.install) {
    add('before_script:');
    if (config.language === 'ruby') {
      add('  - bundle config set --local path vendor/ruby');
    }
    add(`  - ${lang.install}`);
    add();
  }

  // Services block for jobs that need them
  const serviceImages = config.services.map(sId => {
    const svc = SERVICES.find(s => s.id === sId);
    return svc;
  }).filter(Boolean);

  // ---- LINT ----
  if (config.lint && lang.lint) {
    add('lint:');
    add('  stage: lint');
    if (config.language === 'python' && config.lint) {
      add('  before_script:');
      add('    - pip install -r requirements.txt');
      add('    - pip install flake8 mypy');
    }
    if (config.language === 'docker') {
      add('  image: hadolint/hadolint:latest-alpine');
      add('  script:');
      add('    - hadolint Dockerfile');
    } else {
      add('  script:');
      add(`    - ${lang.lint}`);
    }
    if (config.allowLintFailure) {
      add('  allow_failure: true');
    }
    if (config.runnerTag) {
      add('  tags:');
      add(`    - ${config.runnerTag}`);
    }
    add();
  }

  // ---- TEST ----
  if (config.test && lang.test) {
    add('test:');
    add('  stage: test');

    // Services for test job
    if (serviceImages.length > 0) {
      add('  services:');
      serviceImages.forEach(svc => {
        add(`    - name: ${svc.image}`);
        add(`      alias: ${svc.id}`);
      });
      // Service variables
      const svcVars = {};
      serviceImages.forEach(svc => {
        Object.entries(svc.envs).forEach(([k, v]) => { svcVars[k] = v; });
      });
      if (Object.keys(svcVars).length > 0) {
        add('  variables:');
        Object.entries(svcVars).forEach(([k, v]) => add(`    ${k}: "${v}"`));
      }
    }

    add('  script:');
    add(`    - ${lang.test}`);

    // Coverage regex
    if (config.coverage) {
      if (config.language === 'nodejs') add('  coverage: \'/Lines\\s*:\\s*(\\d+\\.?\\d*)%/\'');
      else if (config.language === 'python') add('  coverage: \'/TOTAL.*?(\\d+\\.?\\d*)%/\'');
      else if (config.language === 'go') add('  coverage: \'/coverage: (\\d+\\.?\\d*)% of statements/\'');
      else if (config.language === 'java') add('  coverage: \'/Total.*?(\\d+)%/\'');
      else if (config.language === 'dotnet') add('  coverage: \'/Total\\s*\\|\\s*(\\d+\\.?\\d*)%/\'');
    }

    // Artifacts (test reports)
    if (config.testArtifacts) {
      add('  artifacts:');
      add('    when: always');
      add('    reports:');
      if (config.language === 'nodejs') {
        add('      junit: junit.xml');
      } else if (config.language === 'python') {
        add('      junit: report.xml');
      } else if (config.language === 'go') {
        add('      junit: report.xml');
      } else if (config.language === 'java' || config.language === 'java-gradle') {
        add('      junit: "**/target/surefire-reports/TEST-*.xml"');
      } else {
        add('      junit: report.xml');
      }
    }

    if (config.runnerTag) {
      add('  tags:');
      add(`    - ${config.runnerTag}`);
    }
    add();
  }

  // ---- BUILD ----
  if (config.build) {
    if (config.deploy === 'docker-registry' || config.deploy === 'kubernetes' || config.deploy === 'aws-ecs' || config.deploy === 'heroku') {
      // Docker build
      add('build:');
      add('  stage: build');
      add('  image: docker:27');
      add('  services:');
      add('    - docker:27-dind');
      add('  variables:');
      add('    DOCKER_TLS_CERTDIR: "/certs"');
      add('  before_script:');
      add('    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY');
      add('  script:');
      add('    - docker build -t "$DOCKER_IMAGE:$DOCKER_TAG" -t "$DOCKER_IMAGE:latest" .');
      add('    - docker push "$DOCKER_IMAGE:$DOCKER_TAG"');
      add('    - docker push "$DOCKER_IMAGE:latest"');
      if (config.runnerTag) {
        add('  tags:');
        add(`    - ${config.runnerTag}`);
      }
      if (config.onlyMain) {
        add('  rules:');
        add('    - if: $CI_COMMIT_BRANCH == "main"');
      }
    } else if (lang.build) {
      // Language build
      add('build:');
      add('  stage: build');
      add('  script:');
      add(`    - ${lang.build}`);
      add('  artifacts:');
      add('    paths:');
      if (config.language === 'nodejs') add('      - dist/');
      else if (config.language === 'go') add('      - app');
      else if (config.language === 'java') add('      - target/*.jar');
      else if (config.language === 'java-gradle') add('      - build/libs/*.jar');
      else if (config.language === 'rust') add('      - target/release/');
      else if (config.language === 'dotnet') add('      - out/');
      else add('      - build/');
      add('    expire_in: 1 hour');
      if (config.runnerTag) {
        add('  tags:');
        add(`    - ${config.runnerTag}`);
      }
      if (config.onlyMain) {
        add('  rules:');
        add('    - if: $CI_COMMIT_BRANCH == "main"');
      }
    }
    add();
  }

  // ---- DEPLOY ----
  if (config.deploy !== 'none') {
    const deployEnvs = config.deployStaging ? ['staging', 'production'] : ['production'];

    deployEnvs.forEach((env, idx) => {
      const jobName = deployEnvs.length > 1 ? `deploy_${env}` : 'deploy';
      add(`${jobName}:`);
      add('  stage: deploy');

      switch (config.deploy) {
        case 'docker-registry':
          add('  image: docker:27');
          add('  services:');
          add('    - docker:27-dind');
          add('  before_script:');
          add('    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY');
          add('  script:');
          add(`    - echo "Image pushed in build stage: $DOCKER_IMAGE:$DOCKER_TAG"`);
          add('    - echo "Deploy to ' + env + ' complete"');
          break;

        case 'kubernetes':
          add('  image: bitnami/kubectl:latest');
          add('  script:');
          add(`    - kubectl config use-context $KUBE_CONTEXT`);
          add(`    - sed -i "s|__IMAGE__|$DOCKER_IMAGE:$DOCKER_TAG|g" k8s/${env}/deployment.yaml`);
          add(`    - kubectl apply -f k8s/${env}/`);
          add(`    - kubectl rollout status deployment/app -n ${env} --timeout=300s`);
          break;

        case 'ssh':
          add('  image: alpine:latest');
          add('  before_script:');
          add('    - apk add --no-cache openssh-client');
          add('    - eval $(ssh-agent -s)');
          add('    - echo "$SSH_PRIVATE_KEY" | ssh-add -');
          add('    - mkdir -p ~/.ssh && chmod 700 ~/.ssh');
          add('    - ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts');
          add('  script:');
          if (config.build && (config.language === 'nodejs' || config.language === 'go' || config.language === 'dotnet')) {
            add('    - scp -r dist/* "$DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH"');
          } else {
            add('    - ssh "$DEPLOY_USER@$DEPLOY_HOST" "cd $DEPLOY_PATH && git pull && docker compose up -d --build"');
          }
          break;

        case 'aws-ecs':
          add('  image: amazon/aws-cli:latest');
          add('  script:');
          add(`    - aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE_${env.toUpperCase()} --force-new-deployment`);
          add('    - aws ecs wait services-stable --cluster $ECS_CLUSTER --services $ECS_SERVICE_' + env.toUpperCase());
          break;

        case 'pages':
          add('  script:');
          if (config.language === 'nodejs') {
            add('    - npm run build');
            add('    - mv dist public || mv build public || mv out public');
          } else {
            add('    - mkdir -p public');
            add('    - cp -r build/* public/ || cp -r dist/* public/');
          }
          add('  artifacts:');
          add('    paths:');
          add('      - public');
          break;

        case 'heroku':
          add('  image: docker:27');
          add('  services:');
          add('    - docker:27-dind');
          add('  script:');
          add('    - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com');
          add(`    - docker build -t registry.heroku.com/$HEROKU_APP_${env.toUpperCase()}/web .`);
          add(`    - docker push registry.heroku.com/$HEROKU_APP_${env.toUpperCase()}/web`);
          add(`    - apk add --no-cache curl && curl -n -X PATCH https://api.heroku.com/apps/$HEROKU_APP_${env.toUpperCase()}/formation -d '{"updates":[{"type":"web","docker_image":"'$(docker inspect registry.heroku.com/$HEROKU_APP_${env.toUpperCase()}/web --format={{.Id}})\'"}]}' -H "Content-Type: application/json" -H "Accept: application/vnd.heroku+json; version=3.docker-releases" -H "Authorization: Bearer $HEROKU_API_KEY"`);
          break;

        case 's3':
          add('  image: amazon/aws-cli:latest');
          add('  script:');
          add(`    - aws s3 sync ./dist s3://$S3_BUCKET_${env.toUpperCase()} --delete`);
          if (env === 'production') {
            add('    - aws cloudfront create-invalidation --distribution-id $CF_DISTRIBUTION_ID --paths "/*"');
          }
          break;
      }

      // Environment
      add('  environment:');
      add(`    name: ${env}`);
      if (config.deploy === 'pages') {
        add('    url: https://$CI_PROJECT_NAMESPACE.gitlab.io/$CI_PROJECT_NAME');
      }

      // Rules
      add('  rules:');
      if (env === 'staging') {
        add('    - if: $CI_COMMIT_BRANCH == "main"');
      } else if (env === 'production') {
        if (config.deployStaging) {
          add('    - if: $CI_COMMIT_TAG =~ /^v\\d+\\.\\d+\\.\\d+$/');
          if (config.manualDeploy) add('      when: manual');
        } else {
          add('    - if: $CI_COMMIT_BRANCH == "main"');
          if (config.manualDeploy) add('      when: manual');
        }
      }

      if (config.runnerTag) {
        add('  tags:');
        add(`    - ${config.runnerTag}`);
      }

      add();
    });
  }

  return lines.join('\n').replace(/\n{3,}/g, '\n\n').trim() + '\n';
}

const Toggle = ({ checked, onChange, label, desc }) => (
  <label className="flex items-start gap-3 cursor-pointer group py-1.5">
    <div className={`relative w-9 h-5 rounded-full flex-shrink-0 mt-0.5 transition-colors ${checked ? 'bg-brand-500' : 'bg-dark-700'}`} onClick={(e) => { e.preventDefault(); onChange(!checked); }}>
      <div className={`absolute top-0.5 w-4 h-4 rounded-full bg-white shadow-sm transition-transform ${checked ? 'translate-x-4' : 'translate-x-0.5'}`} />
    </div>
    <div>
      <div className="text-sm text-dark-100 font-medium">{label}</div>
      {desc && <div className="text-[11px] text-dark-500 mt-0.5">{desc}</div>}
    </div>
  </label>
);

const Chip = ({ selected, onClick, children, icon }) => (
  <button onClick={onClick} className={`px-3 py-2 rounded-lg text-[13px] font-medium transition-all border ${selected ? 'bg-brand-500/15 border-brand-400/40 text-brand-300' : 'bg-dark-800 border-dark-700 text-dark-400 hover:border-dark-500'}`}>
    {icon && <span className="mr-1.5">{icon}</span>}{children}
  </button>
);

export default function Client() {
  const [config, setConfig] = useState({
    language: 'nodejs',
    version: '20',
    lint: true,
    test: true,
    build: true,
    deploy: 'docker-registry',
    services: [],
    cache: true,
    coverage: true,
    testArtifacts: false,
    allowLintFailure: false,
    deployStaging: false,
    manualDeploy: true,
    onlyMain: true,
    runnerTag: '',
  });
  const [copied, setCopied] = useState(false);

  const set = useCallback((key, val) => {
    setConfig(prev => {
      const next = { ...prev, [key]: val };
      // Auto-set version when language changes
      if (key === 'language') {
        const lang = LANGUAGES.find(l => l.id === val);
        next.version = lang.versions[0] || '';
        // Reset deploy to none if docker-only and pages selected
        if (val === 'docker' && next.deploy === 'pages') next.deploy = 'docker-registry';
      }
      return next;
    });
  }, []);

  const toggleService = useCallback((sId) => {
    setConfig(prev => ({
      ...prev,
      services: prev.services.includes(sId)
        ? prev.services.filter(s => s !== sId)
        : [...prev.services, sId],
    }));
  }, []);

  const lang = LANGUAGES.find(l => l.id === config.language);
  const yaml = useMemo(() => generateYAML(config), [config]);

  const lineCount = yaml.split('\n').length;

  const copy = () => {
    navigator.clipboard.writeText(yaml);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const download = () => {
    const blob = new Blob([yaml], { type: 'text/yaml' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = '.gitlab-ci.yml';
    a.click();
    URL.revokeObjectURL(a.href);
  };

  // Count required CI/CD variables
  const requiredVars = useMemo(() => {
    const vars = [];
    if (config.deploy === 'ssh') vars.push('SSH_PRIVATE_KEY', 'DEPLOY_HOST', 'DEPLOY_USER', 'DEPLOY_PATH');
    if (config.deploy === 'aws-ecs') vars.push('AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY', 'ECS_CLUSTER', 'ECS_SERVICE_PRODUCTION');
    if (config.deploy === 'heroku') vars.push('HEROKU_API_KEY', 'HEROKU_APP_PRODUCTION');
    if (config.deploy === 'kubernetes') vars.push('KUBE_CONTEXT');
    if (config.deploy === 's3') vars.push('AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY', 'S3_BUCKET_PRODUCTION', 'CF_DISTRIBUTION_ID');
    if (config.deployStaging) {
      if (config.deploy === 'aws-ecs') vars.push('ECS_SERVICE_STAGING');
      if (config.deploy === 'heroku') vars.push('HEROKU_APP_STAGING');
      if (config.deploy === 's3') vars.push('S3_BUCKET_STAGING');
    }
    return vars;
  }, [config.deploy, config.deployStaging]);

  return (
    <ToolLayout title="GitLab CI/CD Generator" description="Build a .gitlab-ci.yml pipeline config. Pick your stack, configure stages, download the file.">
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* LEFT: Config */}
        <div className="space-y-5">
          {/* Language */}
          <div>
            <div className={labelClass}>Language / Framework</div>
            <div className="flex flex-wrap gap-2">
              {LANGUAGES.map(l => (
                <Chip key={l.id} selected={config.language === l.id} onClick={() => set('language', l.id)} icon={l.icon}>{l.label}</Chip>
              ))}
            </div>
          </div>

          {/* Version */}
          {lang.versions.length > 0 && (
            <div>
              <div className={labelClass}>Version</div>
              <div className="flex gap-2">
                {lang.versions.map(v => (
                  <Chip key={v} selected={config.version === v} onClick={() => set('version', v)}>{v}</Chip>
                ))}
              </div>
            </div>
          )}

          {/* Stages */}
          <div>
            <div className={labelClass}>Pipeline Stages</div>
            <div className="space-y-1">
              <Toggle checked={config.lint} onChange={v => set('lint', v)} label="Lint" desc={lang.lint || 'Static analysis'} />
              <Toggle checked={config.test} onChange={v => set('test', v)} label="Test" desc={lang.test || 'Run tests'} />
              <Toggle checked={config.build} onChange={v => set('build', v)} label="Build" desc={config.deploy === 'docker-registry' || config.deploy === 'kubernetes' || config.deploy === 'aws-ecs' ? 'Docker build & push' : (lang.build || 'Compile / bundle')} />
            </div>
          </div>

          {/* Deploy Target */}
          <div>
            <div className={labelClass}>Deploy Target</div>
            <div className="flex flex-wrap gap-2">
              {DEPLOY_TARGETS.map(d => (
                <Chip key={d.id} selected={config.deploy === d.id} onClick={() => set('deploy', d.id)}>{d.label}</Chip>
              ))}
            </div>
            {config.deploy !== 'none' && (
              <div className="text-[11px] text-dark-500 mt-2">
                {DEPLOY_TARGETS.find(d => d.id === config.deploy)?.desc}
              </div>
            )}
          </div>

          {/* Services */}
          <div>
            <div className={labelClass}>Test Services</div>
            <div className="flex flex-wrap gap-2">
              {SERVICES.map(s => (
                <Chip key={s.id} selected={config.services.includes(s.id)} onClick={() => toggleService(s.id)} icon={s.id === 'postgres' ? '🐘' : s.id === 'redis' ? '🔴' : s.id === 'mysql' ? '🐬' : '🍃'}>{s.label}</Chip>
              ))}
            </div>
          </div>

          {/* Options */}
          <div>
            <div className={labelClass}>Options</div>
            <div className="space-y-1">
              <Toggle checked={config.cache} onChange={v => set('cache', v)} label="Cache dependencies" desc="Speed up pipelines with cached node_modules, vendor, etc." />
              <Toggle checked={config.coverage} onChange={v => set('coverage', v)} label="Coverage reporting" desc="Extract test coverage % in merge requests" />
              <Toggle checked={config.testArtifacts} onChange={v => set('testArtifacts', v)} label="JUnit test reports" desc="Show test results in GitLab merge request UI" />
              <Toggle checked={config.allowLintFailure} onChange={v => set('allowLintFailure', v)} label="Allow lint failure" desc="Pipeline continues even if lint fails" />
              {config.deploy !== 'none' && (
                <>
                  <Toggle checked={config.deployStaging} onChange={v => set('deployStaging', v)} label="Staging → Production" desc="Deploy to staging on push, production on tags" />
                  <Toggle checked={config.manualDeploy} onChange={v => set('manualDeploy', v)} label="Manual production deploy" desc="Require manual approval for production" />
                  <Toggle checked={config.onlyMain} onChange={v => set('onlyMain', v)} label="Build only on main" desc="Skip build/deploy for feature branches" />
                </>
              )}
            </div>
          </div>

          {/* Runner tag */}
          <div>
            <div className={labelClass}>Runner Tag (optional)</div>
            <input
              type="text"
              value={config.runnerTag}
              onChange={e => set('runnerTag', e.target.value)}
              placeholder="e.g. docker, self-hosted, gpu"
              className="w-full bg-dark-900 border border-dark-700 rounded-lg px-3 py-2 font-mono text-[13px] text-dark-100 outline-none"
            />
          </div>
        </div>

        {/* RIGHT: Generated YAML */}
        <div>
          <div className="flex items-center justify-between mb-2">
            <div className="flex items-center gap-3">
              <span className="text-xs font-semibold text-dark-400 tracking-wider uppercase">.gitlab-ci.yml</span>
              <span className="text-[10px] text-dark-600">{lineCount} lines</span>
            </div>
            <div className="flex gap-2">
              <button onClick={copy} className={btnSecondary + " !py-1.5 !px-3 !text-[11px]"}>
                {copied ? '✓ Copied' : 'Copy'}
              </button>
              <button onClick={download} className={btnPrimary + " !py-1.5 !px-3 !text-[11px]"}>
                Download
              </button>
            </div>
          </div>

          <pre className="bg-dark-900 rounded-xl border border-dark-700 p-4 font-mono text-[12px] text-dark-200 overflow-auto leading-relaxed" style={{ maxHeight: '70vh', minHeight: '400px', tabSize: 2 }}>
            {yaml}
          </pre>

          {/* Required Variables */}
          {requiredVars.length > 0 && (
            <div className="mt-4 bg-dark-800/50 border border-dark-700 rounded-xl p-4">
              <div className="text-xs font-semibold text-amber-400 mb-2">⚠ Required CI/CD Variables</div>
              <div className="text-[11px] text-dark-400 mb-2">
                Add these in GitLab → Settings → CI/CD → Variables:
              </div>
              <div className="flex flex-wrap gap-1.5">
                {requiredVars.map(v => (
                  <code key={v} className="bg-dark-900 px-2 py-0.5 rounded text-[11px] text-dark-300 font-mono">{v}</code>
                ))}
              </div>
            </div>
          )}

          {/* Pipeline visualization */}
          <div className="mt-4 flex items-center gap-2 overflow-x-auto pb-2">
            {[
              config.lint && 'lint',
              config.test && 'test',
              config.build && 'build',
              config.deploy !== 'none' && (config.deployStaging ? 'deploy_staging' : 'deploy'),
              config.deploy !== 'none' && config.deployStaging && 'deploy_prod',
            ].filter(Boolean).map((stage, i, arr) => (
              <div key={stage} className="flex items-center gap-2">
                <div className="bg-dark-800 border border-dark-600 rounded-lg px-3 py-1.5 text-[11px] font-mono text-dark-300 whitespace-nowrap">
                  {stage}
                </div>
                {i < arr.length - 1 && <span className="text-dark-600">→</span>}
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* SEO content */}
      <section className="mt-10 border-t border-dark-700 pt-6">
        <h2 className="text-base font-bold text-dark-200 mb-3">About GitLab CI/CD Pipeline Configuration</h2>
        <div className="text-xs text-dark-400 leading-relaxed space-y-2">
          <p>GitLab CI/CD uses a <code className="text-dark-300">.gitlab-ci.yml</code> file in the root of your repository to define your pipeline. Each pipeline consists of stages (like lint, test, build, deploy) that run in sequence, with jobs in the same stage running in parallel.</p>
          <p><strong className="text-dark-300">Stages</strong> define the order of execution. A common pattern is lint → test → build → deploy. If any job in a stage fails, the next stage won&apos;t run (unless configured with <code className="text-dark-300">allow_failure: true</code>). <strong className="text-dark-300">Services</strong> like PostgreSQL or Redis can be attached to jobs for integration testing — they run as Docker containers alongside your job.</p>
          <p><strong className="text-dark-300">Caching</strong> speeds up pipelines by preserving directories like <code className="text-dark-300">node_modules</code> or <code className="text-dark-300">.pip-cache</code> between runs. <strong className="text-dark-300">Artifacts</strong> pass files between stages — for example, the build stage produces a binary that the deploy stage uses. <strong className="text-dark-300">Rules</strong> control when jobs run: deploy only on the main branch, or require manual approval for production.</p>
          <p>This generator creates production-ready pipelines following GitLab CI/CD best practices. It supports Docker-in-Docker builds, multi-environment deployments (staging → production), coverage reporting in merge requests, and JUnit test report integration. All configuration runs in your browser — no data is sent to any server.</p>
        </div>
      </section>
    </ToolLayout>
  );
}
